title: Vacillation
description: Vacillation; Fascinated, and procrastinated
baseurl: ""
url: ""
theme: minima

# Collections for organizing content
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:slug/

# Default settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Markdown processor
markdown: kramdown
